# configuration for "master" branch
-
  branches:
    only:
      - master
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  environment:
    apiKey:
      secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
  before_build:
    - ps: gitversion /l console /output buildserver
  - nuget setapikey %apiKey% -Verbosity quiet
  build_script:
  - build.bat NuPlug\NuPlug.csproj /t:Deploy /v:m
#  after_build:
#  - ps: >-
#      $wc = New-Object 'System.Net.WebClient'
#    
#      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\NuPlug.Tests.xml))

# all other branches
-
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  before_build:
    - ps: gitversion /l console /output buildserver
  build_script:
    - build.bat OneClickBuild\OneClickBuild.csproj /t:Package /v:m
 # after_build:
 # - ps: >-
 #     $wc = New-Object 'System.Net.WebClient'
 #   
 #     $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\NuPlug.Tests.xml))
