# configuration for "master" branch
-
  branches:
    only:
      - master
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  environment:
    apiKey:
      secure: lrwREUV4nO99AU0A6xVx/MNF0BaJc8A1B8dwEGMLqmYKGqD5E7PJ/IC9RHcle6pk
  before_build:
    - ps: gitversion /l console /output buildserver
    - nuget setapikey %apiKey% -Verbosity quiet
  build_script:
  - build.bat NuPlug\NuPlug.csproj /t:Test;Deploy /v:m

# all other branches
-
  install:
    - choco install gitversion.portable -pre -y
  test: off
  assembly_info:
    patch: false
  nuget:
    disable_publish_on_pr: true
  environment:
    apiKey:
      secure: nOI+DF6dG2DnZOaNxLKvfpP5RW8Mc6peyzCcnIIFndE=
    NuGetSourceToDeploy: https://ci.appveyor.com/nuget/awesome-inc-build-y5l243ydeuam/api/v2/package
  before_build:
    - ps: gitversion /l console /output buildserver
    - nuget setapikey %apiKey% -Source %NuGetSourceToDeploy% -Verbosity quiet
  build_script:
    - build.bat NuPlug\NuPlug.csproj /t:Test;Deploy /v:m
